openapi: 3.0.3
info:
  title: Ingredients API
  version: 1.0.0

servers:
  - url: http://localhost:3000/v1
    description: Local développement

paths:
  /ingredients:
    get:
      summary: Liste des ingrédients
      responses:
        '200':
          description: Retourne la liste des ingrédients enregistrés 
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/Ingredient'
                example:
                  - id: 1
                    nom: Tomate
                    categorie: Vegetable
                    prix: 1.80
                  - id: 2
                    nom: Pomme
                    categorie: Vegetable
                    prix: 0.90
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema: 
                type: string
              example: "Erreur du chargement de la liste des ingrédients"

  /ingredients/{id}:
    get:
      summary: Récupération d'un ingrédient
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant unique de l'ingrédient
          schema:
            type: integer
            example: 2
      responses:
        '200':
          description: Ingredient récupéré
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Ingredient'
              example:
                - id: 2
                  nom: Poulet
                  categorie: Animal
                  prix: 56.2
        '404':
          description: Erreur lors du chargement de l'ingrédient
          content:
            application/json:
              schema: 
                type: string
              example: "Ingredient.id={2} n'est pas trouvé"



components:
  schemas:
    Ingredient:
      type: object
      properties:
        id: 
          type: integer
          description: Identifiant de l'ingrédient
        nom: 
          type: string
          description: Nom de l'ingrédient
        categorie:
          type: string
          description: Catégorie de l'ingrédient
        prix: 
          type: number
          description: Prix de l'ingrédient